# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41

---
# board: [ "seeeduino_xiao_ble" ]
# shield: [ "kretstrad_v2_left", "kretstrad_v2_right", "settings_reset" ]

include:
#- board: seeeduino_xiao_ble
#   shield: kretstrad_v2_left rgbled_adapter
#   # snippet: zmk-usb-logging

#- board: seeeduino_xiao_ble
#   shield: kretstrad_v2_right rgbled_adapter
#   # snippet: zmk-usb-logging

- board: seeeduino_xiao_ble
  shield: settings_reset

# - board: seeeduino_xiao_ble
#   shield: kretstrad_left

 - board: seeeduino_xiao_ble
   shield: kretstrad_right
