file_format: "1"
id: kretstrad_v2
name: Kretstrad Rev2
type: shield
url: https://github.com/wj-zhe/Kretstrad
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - kretstrad_v2_left
  - kretstrad_v2_right
